apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003
  selector:
    service: reverseproxy