apiVersion: v1
kind: Service
metadata:
  name: feed
spec:
  type: LoadBalancer
  selector:
    service: feed
  ports:
  - name: "8080"
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001 # Port on the node to expose to load balancer. Security group of node must accept traffic on that port from load balancer.