apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USERNAME: mohamed
  POSTGRES_HOST: my-postgres-db.c960mmw2cr36.eu-central-1.rds.amazonaws.com
  AWS_REGION: eu-central-1
  AWS_PROFILE: default
  AWS_BUCKET: my-cool-pic-bucket-with-randomness-123456
