apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: feed-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feed        # HPA for feed deployment
  minReplicas: 2       # Minimum number of pods
  maxReplicas: 10      # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70   # Scale if avg CPU > 70%
