apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# order to which manifests apply
resources:
  - secrets.yaml
  - configmap.yaml
  - application-service.yaml
  - application-deployment.yaml
  - hpa-deployment.yaml
namespace: default
